# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b5de69367eef244891d01243045eb4f36ed676d02b693b9c2aeade6929c420990fc9495be93569b4495cd47306d972a70fba8c37562aa216e20722ed981f9869

test:
  secret_key_base: 0198ce395a0b285d7b169ad8c12db6db456388b53743e15a0f1600a31185e078e9dcfc798a5b554391f4c74498ffde0020ffcf772d95c2f5dd00182de2ef4bdd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
